import { createElement } from 'lwc';
import ConditonalRendering3_button from 'c/conditonalRendering3_button';

describe('c-conditonal-rendering3-button', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-conditonal-rendering3-button', {
            is: ConditonalRendering3_button
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});