
public class StringAssignment {
    public void assisgnment(){

String localString = 'thank you for string session';

Integer lenOfString=localString();
System.debug('length of'+ lenOfString);

String cap=localString.toUpperCase();
System.debug('cap->'+ cap);

Boolean ses1 =localString.contains('session');
System.debug('contains session'+ses1);

Boolean ses=localString.contains('SESSION');
System.debug('contains session'+ses);

Id creat= '001Do000003CNwwIAG';
string belong= 'this id belongs to Pryramid Construction';
Boolean pryramid=true
System debug ('this Id belong'+creat+ belong+pryramid)

    }
}