DmlDemo.dmlInsertDemo_stnObj(); 
//DmlDemo.dmlinsertdemo_cstobject();
//DmlDemo.dmlupdatedemo_1();
DmlDemo.dmlupdatedemo_3();
DmlDemo.dmlupdatedemo_4();
DmlDemo.dmlInsertDemo_5();
DmlDemo.dmlInsertMultiple_right();
//DmlDemo.dmlUpdateMultiple_right1();
//list <account> delcc=[select id from account where name like '%b.o%'];
//delete delcc;
// 2 way 
//delete [select id from account where createddate = This_week];